name: Hop

on:
  push:
    branches: [ "main" ]
    tags:     'v*'
  pull_request:

jobs:
  linuxXlinux:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get install -y build-essential mesa-common-dev libx11-dev libxrandr-dev libgl1-mesa-dev libglu1-mesa-dev libfreetype6-dev libopenal-dev libsndfile1-dev libudev-dev 

    - name: linux-linux
      # Build your program with the given configuration
      run: |
        ./dependencies.sh && ./build.sh -t 
        mkdir linuxbuild 
        cp build/Jerboa linuxbuild/ 
        cp -r resources linuxbuild/ 
        cp tile.hmap linuxbuild/
        zip linuxbuild.zip linuxbuild

    - name: Tests
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest
    - name: buildArtifact
      uses: actions/upload-artifact@v3
      with:
        name: linuxbuild
        path: linuxbuild.zip
    
  linuxXwindows:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get install -y build-essential mesa-common-dev libx11-dev libxrandr-dev libgl1-mesa-dev libglu1-mesa-dev libfreetype6-dev libopenal-dev libsndfile1-dev libudev-dev g++-mingw-w64-x86-64-posix gcc-mingw-w64-x86-64-posix

    - name: linux-X-windows
      # Build your program with the given configuration
      run: |
        ./dependencies.sh -w && ./build.sh -w -t 
        mkdir windowsbuild 
        cp build/Jerboa.exe windowsbuild/ 
        cp -r resources windowsbuild/ 
        cp tile.hmap windowsbuild/ 
        cp -r include/lib/windows/* windowsbuild
        zip windowsbuild.zip windowsbuild
    
    - name: buildArtifact
      uses: actions/upload-artifact@v3
      with:
        name: windowsbuild
        path: windowsbuild.zip
      
  linuxRun:
    needs: linuxXlinux
    runs-on: ubuntu-18.04
    
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y xvfb x11-apps imagemagick

      - name: get linux build
        uses: actions/download-artifact@v3
        with:
          name: linuxbuild

      - name: launch and screenshot
        run: |
          unzip linuxbuild.zip
          cd linuxbuild
          chmod +x Jerboa
          export DISPLAY=:99
          sudo Xvfb :99 -screen 0 800x600x24 &
          sleep 5
          MESA_GL_VERSION_OVERRIDE=3.3 ./Jerboa &
          sleep 10
          xwd -root -silent | convert xwd:- png:screenshot.png
          
          
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: screenshot.png
          
  release:
    needs: [linuxXlinux, linuxXwindows]
    if: github.ref_type == 'tag'
    runs-on: ubuntu-18.04
    
    steps:
      - name: get linux build
        uses: actions/download-artifact@v3
        with:
          name: linuxbuild
          
      - name: get windows build
        uses: actions/download-artifact@v3
        with:
          name: windowsbuild
        
      - name: create release
        id: createRelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          release_name: "release-${{ github.ref_name }}"
          tag_name: ${{ github.ref }}
      
      - name: upload linux release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.createRelease.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: linuxbuild.zip
          asset_name: linux
          asset_content_type: application/zip
          
      - name: upload windows release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.createRelease.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: windowsbuild.zip
          asset_name: windows
          asset_content_type: application/zip

    

